make prueba_TS

./prueba_TS buscarParaDeclararProcedural_aop.in buscarParaDeclararProcedural_n.out
./prueba_TS buscarIdEnJerarquiaDesdeClase_aop.in buscarIdEnJerarquiaDesdeClase_n.out
./prueba_TS declararMiembroInstancia_aop.in declararMiembroInstancia_n.out
./prueba_TS buscarIdNoCualificado_aop.in buscarIdNoCualificado_n.out
./prueba_TS declararMiembrosClase_aop.in declararMiembrosClase_n.out
./prueba_TS idCualificadoInstanciaClase_aop.in idCualificadoInstanciaClase_n.out
./prueba_TS declararIdLocalMetodo_aop.in declararIdLocalMetodo_n.out
