CC = gcc
CCFLAGS = -Wall -g

all:  omicron

omicron: *.c
	gcc -o prueba_TS *.c -lm



clean:
	rm -f hash_table.o node.o graph.o
	rm -f  generacion.o y.tab.c y.tab.h y.output lex.yy.c y.tab.o lex.yy.o omicron